---
name: submariner
version: 0.0.4
appVersion: v0.0.4
description: k8s 1.16.x support
keywords:
home: https://submariner-io.github.io/
sources:
  - https://submariner-io.github.io/submariner-charts/charts
maintainers:
  - name: Submariner Developers
    email: submariner-dev@googlegroups.com
